# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FnLock.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FnLock(object):
    def setupUi(self, FnLock):
        FnLock.setObjectName("FnLock")
        FnLock.resize(174, 87)
        self.checkBox = QtWidgets.QCheckBox(FnLock)
        self.checkBox.setGeometry(QtCore.QRect(60, 20, 80, 40))
        self.checkBox.setMinimumSize(QtCore.QSize(0, 40))
        self.checkBox.setMaximumSize(QtCore.QSize(80, 40))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(FnLock)
        self.checkBox.stateChanged['int'].connect(FnLock.lock_switch)
        QtCore.QMetaObject.connectSlotsByName(FnLock)

    def retranslateUi(self, FnLock):
        _translate = QtCore.QCoreApplication.translate
        FnLock.setWindowTitle(_translate("FnLock", "FnLock"))
        self.checkBox.setText(_translate("FnLock", "锁定Fn"))
